include:
  - path: observability/docker-compose.yml

services:
  woodwideweb:
    build: .
    ports:
      - "127.0.0.1:3000:80"
    networks:
      - web
    restart: unless-stopped

networks:
  web:
    driver: bridge
